#!/bin/sh


cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd ..

output="${1:-itt_pro.w3x}"
cfg="${2:-${output}.cfg}"
env="${3:-pro}"
dest="${4:-twgbhost}" # /cygdrive/c/Users/Jesse/${dest}

echo "Preparing to build $output"

if [ -f "$output" ]; then
  echo "Removing old ($output) files"
  rm "$output"*
fi

echo "Building $output in $env environment"
./map/build env:$env map_output_path:"../$output" $@

if [ $? != 0 ]; then
  exit
fi

echo "Deploying to clantwgb.com"

echo "Copying $output to $dest"
scp "$output" Jesse@clantwgb.com:"/cygdrive/c/Users/Jesse/${dest}/maps"
echo "Copied!"

echo "Creating ${cfg} and copying to $dest"
sed -e "s/\${output}/${output}/" scripts/itt.cfg.template | sed -e "s/\${env}/${env}/" > tmp.cfg && scp tmp.cfg Jesse@clantwgb.com:"/cygdrive/c/Users/Jesse/${dest}/mapcfgs/${cfg}" && rm tmp.cfg

echo "Finished deploying $output"

exit
