#!/bin/sh


cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd ..

output="${1:-itt_pro.w3x}"
cfg="${2:-${output}.cfg}"

echo "Preparing to build $output"

if [ -f "$output" ]; then
  echo "Removing old ($output) files"
  rm "$output"*
fi

echo "Building $output"
./map/build env:pro map_output_path:"../$output" $@

if [ $? != 0 ]; then
  exit
fi

echo "Copying $output to clantwgb.com"
scp "$output" Jesse@clantwgb.com:"/cygdrive/c/Users/Jesse/twgbhost/maps"
echo "Copied!"

echo "Creating ${cfg}"
sed -e "s/\${output}/${output}/" scripts/itt.cfg.template > tmp.cfg && scp tmp.cfg Jesse@clantwgb.com:"/cygdrive/c/Users/Jesse/twgbhost/mapcfgs/${cfg}" && rm tmp.cfg

echo "Finished deploying $output"

exit
