#!/bin/sh

echo "MySQL connecting to twgb@clantwgb.com:3306"
echo "select user.name, vars.value_string email from w3mmdvars vars inner join w3mmdplayers user on user.pid = vars.pid and user.gameid = vars.gameid where varname = 'email';" | mysql -u twgb -p -h clantwgb.com twgb_ghost > emails.txt

