#!/bin/sh

echo "MySQL connecting to twgb@clantwgb.com:3306"
echo "select user.gameid, user.name, vars.varname, vars.value_string from w3mmdvars vars inner join w3mmdplayers user on user.gameid = vars.gameid and user.pid = vars.pid where varname like 'bug%' order by user.gameid desc limit 20;" | mysql -u twgb -p -h clantwgb.com twgb_ghost > bugs.txt

