#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

dir="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
compiled="out.j"
out="tmp.j"
jh="wine $dir/../tools/jasshelper/clijasshelper.exe --scriptonly $dir/../tools/common.j $dir/../tools/blizzard.j "

function add {
  if [ -d $1 ]; then
    for f in "$1*"; do
      echo "Adding $1*"
      add $f
    done
  fi
  if [ -f $1 ]; then
    echo "Found file $1"
    if [[ $1 == *.zn ]]; then
      echo -e "\n//! zinc" >> $out
      cat $1 >> $out
      echo -e "\n//! endzinc" >> $out
    fi
    if [[ $1 == *.j ]]; then
      cat $1 >> $out
    fi
  fi
}

if [ "--add-main" = $1 ]; then
  echo "function main takes nothing returns nothing" >> $out
  echo "endfunction" >> $out
  shift
fi

for f in $*; do
  add $f
done

$jh $out $compiled
rm $out

echo ""
