#!/bin/sh

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd ..

echo "Enter map output path:"
read output
echo "Attempting to build $output..."

if [ -f "$output" ]; then
  echo "Removing old ($output) files"
  rm "$output"*
fi

./map/build env:pro map_output_path:"../$output"
