#!/bin/bash

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd ..

if [ -f itt_test.w3x ]; then
  rm itt_test.w3x*
fi
./scripts/build env:test map_output_path:"itt_test.w3x" debug_script:true
